spring.application.name=DataTable

# MongoDB Configuration
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=datatable_db
#spring.data.mongodb.username=admin
#spring.data.mongodb.password=secret123
#spring.data.mongodb.authentication-database=admin
spring.data.mongodb.uri=mongodb://admin:secret123@localhost:27017/datatable_db?authSource=admin


gemini.api-key=${GEMINI_API_KEY}
gemini.url=https://generativelanguage.googleapis.com/v1beta

# External Services
application.manager.url=https://datamanager-nokp.onrender.com/api/v1/dataloader/applications


# Server Configuration
server.port=8888

# Logging
logging.level.org.springframework.data.mongodb=DEBUG
